### ISSUE TITLE
Client fails to launch

### ISSUE THREAD

**Issue by Dunkstormen** [Stream-Pi/Client#5] opened 2020-04-29 16:23 UTC
I keep getting the following error when trying to start the client.

> pi@raspberrypi:~/linux_armv7 $ sudo /home/pi/StreamPi/start_streampi

```
Prism pipeline init order: es2 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
System.loadLibrary(prism_es2_monocle) succeeded
	succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
System.loadLibrary(glass_monocle) succeeded
* failed to add service - already in use?
```
I'm running a Raspberry Pi 4 with raspbian installed and using the following touchscreen https://www.raspberrypi.org/products/raspberry-pi-touch-display/

**Comment by dubbadhar** [comment] 2020-05-14 17:25
Pi 4 isnt supported atm because of GPU driver issues (Foundation's Fault :P) 
However, you can still run it, but it use xserver instead of fb, which means performance impact as xserver doesnt leverage hardware acceleration.

In order to run on a pi 4, change your /boot/config.txt to the following :
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=18
hdmi_cvt 1024 600 60 6 0 0 0
# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2
gpu_mem=256
[all]
dtoverlay=vc4-fkms-v3d

# NOOBS Auto-generazaza
```
Then change your start_streampi file to the following :
```
#!/usr/bin/env bash
cd /home/pi/StreamPi/
sudo jdk/bin/java -Djavafx.platform=gtk -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.virtualKeyboard=javafx StreamPiClient.Main
```

Reboot and run again :)

**Comment by dongfanglong2012** [comment] 2020-05-15 22:16
Im having the same problem and did what you said but i get jdk/bin/java command not found.

**Comment by dubbadhar** [comment] 2020-05-16 08:51
@dongfanglong2012 can you show me the output of your `ls`. its highly likely that you are in the incorrect directory

**Comment by dongfanglong2012** [comment] 2020-05-16 14:25
https://imgur.com/Ug5YvDk

it may be i got the wrong version?

**Comment by dongfanglong2012** [comment] 2020-05-16 14:27
also i checked and java is installed. 

java --version
openjdk 11.0.7 2020-04-14

**Comment by dubbadhar** [comment] 2020-05-17 21:30
@dongfanglong2012 can you rename the directory `jdk` to `jre` and try again?

**Comment by dongfanglong2012** [comment] 2020-05-18 23:18
https://imgur.com/gallery/XLPDr8W

that's what happens when i try jre. i tried that before posting but thought since he said use jdk that it wasn't supposed to work with jre. I'm not that experienced with java.

**Comment by dubbadhar** [comment] 2020-05-19 04:53
can you send me output of your `start_streampi` file?

**Comment by dongfanglong2012** [comment] 2020-05-21 00:47
i dont have it with me at the moment but its a strait copy pasta of the command in the above comment. 

`#!/usr/bin/env bash
cd /home/pi/StreamPi/
sudo jdk/bin/java -Djavafx.platform=gtk -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.virtualKeyboard=javafx StreamPiClient.Main`

**Comment by dongfanglong2012** [comment] 2020-05-21 21:37
here is a pastebin of the file 

https://pastebin.com/NVHSmnhW

**Comment by TempestIndra** [comment] 2020-05-24 01:53
Same problem here as well,
here start_streampi output

pi@raspberrypi:~ $ sudo /home/pi/StreamPi/start_streampi
Error: Could not find or load main class StreamPiClient.Main
Caused by: java.lang.ClassNotFoundException: StreamPiClient.Main
pi@raspberrypi:~ $

**Comment by dubbadhar** [comment] 2020-06-10 05:49
@dongfanglong2012 @TempestIndra change the content of your `start_streampi` file to this :
#!/usr/bin/env bash
cd /home/pi/StreamPi/
sudo jre/bin/java -Djavafx.platform=gtk -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.virtualKeyboard=javafx -jar StreamPiClient-0.6.jar

**Comment by dubbadhar** [comment] 2020-06-10 05:52
Closing the issue, since i suppose it has been fixed (Few users from the discord server followed this new one and they reported that its working.

**NOTE : The overall experience can be a bit slow because this method uses software rendering instead of hardware acceleration. This is because the legacy GL driver used by earlier Pis has been removed in Pi 4. It now uses some other driver and the folks at Gluon are working on adding support to it.**

**Closed by dubbadhar** 2020-06-10 05:52 UTC
